In [27]:
import numpy as np
# Size of the points dataset.
m = 20
#定义数据集和学习率
# Points x-coordinate and dummy value (x0, x1).
#ones生成初始值为1，长度为m的一位数组 zeros()初始值为0
X0 = np.ones((m, 1))
#arange(x,y) 一维数组 x是间隔  y是数组最后一位上限，不包含y 
#reshape 将一位数组转换成二维数组，reshape(x,y)x行y列 x*y=一位数组的长度
X1 = np.arange(1, m+1).reshape(m, 1)
X = np.hstack((X0, X1))
print(X)

# Points y-coordinate
y = np.array([
    3, 4, 5, 5, 2, 4, 7, 8, 11, 8, 12,
    11, 13, 13, 16, 17, 18, 17, 19, 21
]).reshape(m, 1)
print(y)
# The Learning Rate alpha.
alpha = 0.01


#以矩阵向量的形式定义代价函数和代价函数的梯度
def error_function(theta, X, y):
    '''Error function J definition.'''
    diff = np.dot(X, theta) - y
    return (1./2*m) * np.dot(np.transpose(diff), diff)

def gradient_function(theta, X, y):
    '''Gradient of the function J definition.'''
    diff = np.dot(X, theta) - y
    # print(diff)
    # grd = np.dot(np.transpose(X), diff)
    # print(grd)
    return (1./m) * np.dot(np.transpose(X), diff)

def gradient_descent(X, y, alpha):
    '''Perform gradient descent.'''
    theta = np.array([1, 1]).reshape(2, 1)
    gradient = gradient_function(theta, X, y)
    while not np.all(np.absolute(gradient) <= 1e-5):
        theta = theta - alpha * gradient
        gradient = gradient_function(theta, X, y)
    return theta

optimal = gradient_descent(X, y, alpha)
print('optimal:', optimal)
print('error function:', error_function(optimal, X, y)[0,0])
# theta = np.array([1, 1]).reshape(2, 1)
# 
# gradient = gradient_function(theta, X, y)
# print(gradient)
# ress= np.absolute(gradient)
# print(ress > 3)
# print(ress)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]
 [ 1. 11.]
 [ 1. 12.]
 [ 1. 13.]
 [ 1. 14.]
 [ 1. 15.]
 [ 1. 16.]
 [ 1. 17.]
 [ 1. 18.]
 [ 1. 19.]
 [ 1. 20.]]
[[ 3]
 [ 4]
 [ 5]
 [ 5]
 [ 2]
 [ 4]
 [ 7]
 [ 8]
 [11]
 [ 8]
 [12]
 [11]
 [13]
 [13]
 [16]
 [17]
 [18]
 [17]
 [19]
 [21]]
optimal: [[0.51583286]
 [0.96992163]]
error function: 405.98496249324046


In [7]:
#以矩阵向量的形式定义代价函数和代价函数的梯度
def error_function(theta, X, y):
    '''Error function J definition.'''
    diff = np.dot(X, theta) - y
    return (1./2*m) * np.dot(np.transpose(diff), diff)

def gradient_function(theta, X, y):
    '''Gradient of the function J definition.'''
    diff = np.dot(X, theta) - y
    return (1./m) * np.dot(np.transpose(X), diff)


theta = np.array([1, 1]).reshape(2, 1)

gradient = gradient_function(theta, X, y)

NameError: name 'X' is not defined

NameError: name 'gradient_function' is not defined

In [23]:
X1 = np.arange(1, 3).reshape(2,1) #.reshape(m, 1)
print(X1)
test2 = np.arange(1,5).reshape(2,2)
print(test2)
print(test2 > 3)


[[1]
 [2]]
[[1 2]
 [3 4]]
[[False False]
 [False  True]]
