In [ ]:
import numpy as np
#ones zeros empty 
np.zeros(3,dtype=int)  #默认是浮点型  一维数组
# array:[0 0 0]

np.zeros([2,3])  #二维数组
#2行3列数组，值=1，默认为float
x3 = np.ones((2,3))
x4 = np.empty(3)

# 创建一个3*5的浮点型数组，数组的值全部为3.14
np.full((3,5),3.14)

# 创建5个元素数组，这5个元素均匀分布到0到1之间
np.linspace(0,1,5)
# array([0.  , 0.25, 0.5 , 0.75, 1.  ])
# 创建一个3*3的在0~1范围内的随机数组成的数组
np.random.random((3,3))
# array([[0.2131937 , 0.99476852, 0.12470957],
#        [0.57641785, 0.00268608, 0.13124108],
#        [0.0626813 , 0.73013671, 0.72995278]])


#arange(x,y,m) 一维数组 x是起始值  y是数组最后一位上限，不包含y  m是间隔
X1 = np.arange(2, 10,2)   
# array([2, 4, 6, 8])
#reshape 将一位数组转换成二维数组，reshape(x,y)x行y列 x*y=一位数组的长度
X1.reshape(2,2)
# array([[2, 4],
#        [6, 8]])

# 创建一个3*3的单位矩阵
np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

In [71]:
a=[1,2,3]
b=[4,5,6]
print(np.hstack((a,b)))

# 输出：[1 2 3 4 5 6 ]
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
d=[[1],[2],[3]]
np.hstack((a,b,c,d))
# array([[1, 1, 1, 1],
#        [2, 2, 2, 2],
#        [3, 3, 3, 3]])

[1 2 3 4 5 6]


array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [72]:
# 创建一个3*3的，[0，10)区间的随机整型数
ranArr1 = np.random.randint(0,10,(3,3))
ranArr2 = np.random.randint(0,5,(3,3))
# randomArr = np.random.randn(3,4,int)
# dot矩阵相乘
dotArr = np.dot(ranArr1,ranArr2)
dotArr



array([[52, 28, 18],
       [50, 31, 16],
       [20, 14, 12]])

In [65]:
#卧槽，真难 参考：https://www.cnblogs.com/sunshinewang/p/6893503.html
#自己的理解
#reshape最后两位参数2,4先组成平面2行4列，
# [[ 0,  1,  2,  3],
#     [ 4,  5,  6,  7]]  

# [[ 8,  9, 10, 11],
#         [12, 13, 14, 15]]
# 第3维长度为2，这里先考虑3维，理解为纵向，两个平面纵向叠加，组成类似魔方的东西
arr1 = np.arange(16).reshape(2,2,4)

# 如果4维，由两个（2,2，2）的立体组成，一个立体由2个二行四列的平面组成，  先把第4维理解为时间，2个立体放在不同时间轴，
arr2 = np.arange(16).reshape(2,2,2,2)

# 转置 transpose
#这里有个索引的概念，索引表示各个维度，索引0:形状2，索引1：形状：2，索引2：形状4
# transpose((1,0,2))表示朝着索引2维度，将索引1和索引0两个维度组成的平面进行转置。前提是有个维度没变更适合swapaxes

#原数组
# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7]],
# 
#        [[ 8,  9, 10, 11],
#         [12, 13, 14, 15]]])
arr1.transpose((2,0,1))
# 转置后数组
# array([[[ 0,  1,  2,  3],
#         [ 8,  9, 10, 11]],
# 
#        [[ 4,  5,  6,  7],
#         [12, 13, 14, 15]]])
# 比如，数值8开始的索引是[1,0,0]，变换后变成了[0,1,0]。 真抽象


# 轴变换，索引1和索引2组成的平面转置就行了
arr1.swapaxes(1,2)
# array([[[ 0,  4],
#         [ 1,  5],
#         [ 2,  6],
#         [ 3,  7]],
# 
#        [[ 8, 12],
#         [ 9, 13],
#         [10, 14],
#         [11, 15]]])
# arr1

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])