In [11]:
import numpy as np
#ones zeros empty 
x1 = np.zeros(3,int)  #默认是浮点型  一维数组

print(x1)
x2 = np.zeros([2,3])  #二维数组
print(x2)
x3 = np.ones((2,3))

x4 = np.empty(3)
x3

[0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#arange(x,y,m) 一维数组 x是起始值  y是数组最后一位上限，不包含y  m是间隔

X1 = np.arange(2, 10,2)   #.               reshape(m, 1)
X1

array([2, 4, 6, 8])

In [15]:
#reshape 将一位数组转换成二维数组，reshape(x,y)x行y列 x*y=一位数组的长度
X1.reshape(2,2)

array([[2, 4],
       [6, 8]])